In [1]:
import torch

In [2]:
TRAIN_SIZE = 10000

Data preparation

In [3]:
from data_generation_sr import generate_expression_tree, tree_to_graph

graphset = []

for i in range(TRAIN_SIZE):
    graphset.append(tree_to_graph(generate_expression_tree()))

ModuleNotFoundError: No module named 'data_generation_sr'

Configuration

In [4]:
cfg = {
    'general': {
        'name': 'experiment_name',
        'log_every_steps': 10,
        'number_chain_steps': 100,
        'sample_every_val': 1,
        'samples_to_generate': 10,
        'samples_to_save': 5,
        'chains_to_save': 5,
        'final_model_samples_to_generate': 50,
        'final_model_samples_to_save': 25,
        'final_model_chains_to_save': 25,
    },
    'model': {
        'diffusion_steps': 100,
        'lambda_train': 0.1,
        'n_layers': 4,
        'hidden_mlp_dims': 256,
        'hidden_dims': 128,
        'diffusion_noise_schedule': 'cosine',
        'transition': 'uniform',
    },
    'train': {
        'lr': 0.001,
        'weight_decay': 0.01,
        'batch_size': 32,
    }
}

Initialising the model

In [5]:
from extra_metrics import TrainMetrics, SamplingMetrics, VizualisationTools, ExtraFeatures, DomaineFeatures

ImportError: cannot import name 'VizualisationTools' from 'extra_metrics' (/Users/pomeret/Desktop/DiGress/extra_metrics.py)

In [ ]:
dataset_infos = {
    'input_dims': {'X': 2, 'E': 1, 'y': 1},
    'output_dims': {'X': 2, 'E': 1, 'y': 1},
    'nodes_dist': torch.distributions.Categorical(torch.tensor([0.5, 0.5])),
    'node_types': torch.tensor([1, 1]),
    'edge_types': torch.tensor([1, 1])
}


train_metrics = TrainMetrics()
sampling_metrics = SamplingMetrics()
visualization_tools = VisualizationTools()
extra_features = ExtraFeatures()
domain_features = DomainFeatures()

model = DiscreteDenoisingDiffusion(cfg, dataset_infos, train_metrics, sampling_metrics, visualization_tools, extra_features, domain_features)


NameError: name 'TrainMetrics' is not defined

Training

In [ ]:
from pytorch_lightning import Trainer
from pytorch_lightning.callbacks import ModelCheckpoint

checkpoint_callback = ModelCheckpoint(
    monitor='val/epoch_NLL',
    dirpath='checkpoints/',
    filename='model-{epoch:02d}-{val/epoch_NLL:.2f}',
    save_top_k=3,
    mode='min',
)

trainer = Trainer(
    max_epochs=100,
    callbacks=[checkpoint_callback],
    gpus=1  # Use the appropriate number of GPUs
)

trainer.fit(model, train_dataloader, val_dataloader)


Inference

In [ ]:
model.eval()
model.to('cuda')  # Move the model to the GPU if available

# Generate samples
samples = model.sample_batch(batch_id=0, batch_size=10, keep_chain=5, number_chain_steps=100, save_final=5)

# Process and visualize the samples
for sample in samples:
    atom_types, edge_types = sample
    print("Atom types:", atom_types)
    print("Edge types:", edge_types)


In [7]:
edge_index = torch.tensor([[   2,    4,    4,    1,    1,    7,    7,    0,    0,   11,   11,   10,
           16,   15,   14,   20,   20,   19,   19,   25,   24,   18,   18,   29,
           29,   28,   33,   32,   32,   27,   27,   38,   38,   37,   37,   36,
           44,   43,   42,   48,   48,   47,   47,   46,   55,   55,   53,   53,
           58,   52,   52,   62,   62,   65,   65,   61,   61,   69,   69,   68,
           60,   60,   74,   76,   73,   73,   72,   80,   82,   79,   79,   85,
           84,   84,   78,   78,   90,   92,   89,   89,   88,   95,   94,   98,
           98,  102,  102,  105,  105,  101,  101,   97,   97,  110,  112,  112,
          109,  109,  108,  117,  117,  120,  116,  116,  123,  123,  126,  126,
          122,  122,  115,  115,  132,  130,  130,  135,  134,  129,  129,  139,
          139,  138,  138,  143,  137,  137,  147,  146,  150,  149,  145,  145,
          154,  156,  156,  153,  153,  159,  152,  152,  162,  164,  161,  161,
          167,  166,  171,  171,  170,  175,  175,  174,  174,  169,  169,  180,
          180,  179,  186,  184,  184,  188,  188,  183,  183,  192,  192,  197,
          195,  195,  191,  191,  201,  203,  203,  200,  200,  206,  199,  199,
          210,  209,  209,  215,  213,  213,  208,  208,  219,  221,  218,  218,
          224,  224,  227,  223,  223,  217,  217,  232,  232,  230,  230,  229,
          237,  237,  236,  236,  235,  243,  242,  245,  241,  241,  249,  249,
          248,  248,  255,  255,  253,  253,  247,  247,  260,  262,  259,  259,
          265,  267,  267,  264,  264,  258,  258,  272,  272,  271,  271,  270,
          278,  277,  281,  283,  283,  280,  280,  276,  276,  288,  288,  291,
          287,  287,  293,  286,  286,  298,  298,  296,  296,  303,  301,  301,
          295,  295,  306,  306,  309,  309,  305,  305,  314,  314,  313,  313,
          312,  319,  321,  318,  318,  325,  325,  324,  323,  330,  330,  329,
          333,  328,  328,  338,  338,  336,  336,  341,  335,  335,  345,  344,
          348,  348,  351,  351,  347,  347,  343,  343,  356,  356,  355,  355,
          362,  362,  360,  360,  354,  354,  367,  369,  369,  366,  366,  372,
          365,  365,  375,  375,  374,  380,  382,  382,  379,  379,  378,  387,
          387,  386,  385,  393,  391,  391,  396,  398,  398,  395,  395,  390,
          390,  403,  402,  401,  407,  407,  410,  410,  406,  406,  405,  415,
          415,  414,  413,  421,  421,  419,  419,  425,  425,  424,  424,  418,
          418,  432,  432,  430,  430,  435,  429,  429,  439,  441,  441,  438,
          438,  437,  447,  447,  445,  445,  451,  453,  453,  450,  450,  444,
          444,  459,  457,  457,  462,  461,  456,  456,  466,  466,  469,  469,
          465,  465,  474,  474,  472,  472,  464,  464,  479,  481,  481,  478,
          478,  485,  484,  477,  477,  488,  487,  491,  494,  493,  493,  490,
          490,  499,  499,  502,  502,  498,  498,  497,  507,  506,  505,  511,
          511,  514,  510,  510,  518,  518,  516,  516,  509,  509,  523,  523,
          522,  527,  526,  521,  521,  532,  530,  530,  529,  536,  535,  535,
          534,  541,  543,  543,  540,  540,  539,  548,  547,  547,  546,  553,
          553,  552,  557,  559,  559,  556,  556,  551,  551,  564,  564,  567,
          563,  563,  570,  569,  562,  562,  574,  576,  576,  573,  573,  580,
          579,  572,  572,  584,  584,  583,  582,  588,  588,  587,  592,  591,
          595,  595,  600,  600,  598,  598,  594,  594,  605,  605,  604,  603,
          611,  609,  609,  608,  615,  614,  614,  613,  620,  620,  623,  623,
          619,  619,  627,  627,  626,  618,  618,  633,  633,  631,  631,  637,
          639,  636,  636,  630,  630,  643,  642,  646,  646,  645,  641,  641,
          651,  651,  650,  649,  656,  658,  655,  655,  654,  661,  661,  665,
          665,  664,  660,  660,  670,  672,  672,  669,  669,  676,  676,  675,
          668,  668,  682,  680,  680,  679,  687,  687,  685,  685,  684,  692,
          691,  695,  697,  694,  694,  690,  690,  701,  701,  700,  706,  706,
          704,  704,  699,  699,  711,  710,  714,  713,  713,  709,  709,  719,
          718,  717,  722,  722,  726,  728,  728,  725,  725,  721,  721,  733,
          735,  732,  732,  738,  738,  741,  741,  737,  737,  731,  731,  746,
          745,  745,  751,  749,  749,  744,  744,  754,  754,  757,  753,  753,
          761,  761,  760,  760,  759,  767,  766,  766,  765,  772,  771,  771,
          770,  776,  779,  781,  778,  778,  775,  775,  785,  784,  784,  783,
          790,  790,  793,  789,  789,  796,  796,  799,  799,  795,  795,  788,
          788,  805,  803,  803,  802,  809,  809,  808,  807,  814,  814,  813,
          812,  819,  821,  821,  818,  818,  824,  817,  817,  828,  828,  827,
          827,  834,  832,  832,  826,  826,  838,  840,  840,  837,  837,  844,
          846,  843,  843,  836,  836,  850,  849,  853,  855,  855,  852,  852,
          848,  848,  860,  860,  859,  865,  865,  863,  863,  858,  858,  871,
          869,  869,  868,  875,  875,  874,  873,  880,  879,  884,  882,  882,
          878,  878,  888,  888,  891,  891,  887,  887,  896,  896,  894,  894,
          886,  886,  901,  900,  899,  906,  904,  904,  903,  910,  912,  912,
          909,  909,  916,  916,  919,  919,  915,  915,  908,  908,  923,  923,
          927,  927,  930,  930,  926,  926,  922,  922,  935,  935,  934,  939,
          941,  941,  938,  938,  933,  933,  946,  946,  949,  945,  945,  944,
          953,  955,  952,  952,  957,  951,  951,  960,  960,  963,  963,  959,
          959,  968,  967,  971,  970,  970,  966,  966,  977,  977,  975,  975,
          981,  981,  980,  974,  974,  987,  985,  985,  984,  990,  993,  993,
          992,  989,  989,  998,  998, 1001, 1001,  997,  997,  996, 1007, 1007,
         1005, 1005, 1011, 1010, 1004, 1004, 1015, 1014, 1013, 1019, 1019, 1018,
         1017, 1023, 1022, 1026, 1025, 1030, 1030, 1033, 1033, 1029, 1029, 1028,
         1038, 1038, 1037, 1037, 1036, 1044, 1044, 1047, 1047, 1043, 1043, 1051,
         1051, 1050, 1042, 1042, 1055, 1057, 1057, 1054, 1054, 1061, 1060, 1065,
         1064, 1069, 1069, 1067, 1067, 1063, 1063, 1074, 1076, 1076, 1073, 1073,
         1072, 1080, 1084, 1084, 1082, 1082, 1079, 1079, 1089, 1089, 1088, 1093,
         1095, 1095, 1092, 1092, 1087, 1087, 1100, 1100, 1103, 1103, 1099, 1099,
         1098, 1108, 1107, 1106, 1111, 1111, 1110, 1116, 1118, 1115, 1115, 1114,
         1122, 1122, 1125, 1125, 1121, 1121, 1129, 1129, 1132, 1132, 1128, 1128,
         1120, 1120, 1137, 1137, 1136, 1140, 1140, 1135, 1135, 1144, 1147, 1149,
         1149, 1146, 1146, 1143, 1143, 1155, 1155, 1153, 1153, 1152, 1160, 1160,
         1159, 1164, 1163, 1163, 1158, 1158, 1169, 1169, 1168, 1168, 1174, 1174,
         1173, 1173, 1167, 1167, 1180, 1179, 1179, 1185, 1185, 1183, 1183, 1178,
         1178, 1190, 1190, 1189, 1189, 1194, 1188, 1188, 1197, 1200, 1200, 1203,
         1199, 1199, 1196, 1196, 1207, 1206, 1206, 1211, 1213, 1213, 1210, 1210,
         1205, 1205, 1218, 1218, 1217, 1217, 1224, 1222, 1222, 1216, 1216, 1228,
         1228, 1227, 1227, 1233, 1233, 1232, 1226, 1226, 1238, 1237, 1237, 1242,
         1241, 1241, 1236, 1236, 1247, 1246, 1250, 1250, 1249, 1245, 1245, 1254,
         1254, 1258, 1257, 1253, 1253, 1262, 1262, 1265, 1261, 1261, 1268, 1267,
         1260, 1260, 1272, 1272, 1275, 1275, 1271, 1271, 1270, 1280, 1280, 1279,
         1284, 1284, 1287, 1287, 1283, 1283, 1278, 1278, 1292, 1291, 1291, 1296,
         1296, 1295, 1290, 1290, 1300, 1304, 1302, 1302, 1299, 1299, 1307, 1307,
         1311, 1310, 1310, 1306, 1306, 1316, 1316, 1319, 1315, 1315, 1322, 1322,
         1325, 1321, 1321, 1314, 1314, 1329, 1329, 1328, 1333, 1332, 1332, 1327,
         1327, 1337, 1337, 1341, 1341, 1340, 1336, 1336, 1346, 1346, 1345, 1345,
         1351, 1350, 1350, 1344, 1344, 1356, 1356, 1359, 1355, 1355, 1362, 1362,
         1361, 1354, 1354, 1367, 1369, 1366, 1366, 1372, 1371, 1365, 1365, 1376,
         1376, 1375, 1379, 1374, 1374, 1384, 1382, 1382, 1387, 1387, 1390, 1386,
         1386, 1381, 1381, 1394, 1393, 1393, 1392, 1398, 1401, 1400, 1400, 1397,
         1397, 1406, 1406, 1405, 1405, 1404, 1411, 1415, 1413, 1413, 1410, 1410,
         1419, 1421, 1421, 1418, 1418, 1425, 1424, 1417, 1417, 1428, 1428, 1431,
         1431, 1427, 1427, 1436, 1438, 1438, 1435, 1435, 1442, 1442, 1441, 1441,
         1434, 1434, 1447, 1450, 1449, 1446, 1446, 1454, 1454, 1453, 1458, 1460,
         1457, 1457, 1452, 1452, 1464, 1463, 1463, 1467, 1462, 1462, 1471, 1471,
         1474, 1474, 1470, 1470, 1469, 1480, 1480, 1478, 1478, 1484, 1484, 1483,
         1477, 1477, 1488, 1488, 1487, 1493, 1493, 1496, 1492, 1492, 1499, 1499,
         1498, 1491, 1491, 1503, 1502, 1507, 1507, 1506, 1511, 1511, 1514, 1510,
         1510, 1505, 1505, 1517, 1520, 1520, 1519, 1516, 1516, 1525, 1527, 1524,
         1524, 1523, 1532, 1532, 1530, 1530, 1536, 1536, 1539, 1539, 1535, 1535,
         1529, 1529, 1544, 1546, 1546, 1543, 1543, 1542, 1551, 1551, 1550, 1549,
         1557, 1557, 1555, 1555, 1554, 1561, 1564, 1564, 1567, 1567, 1563, 1563,
         1560, 1560],
        [   3,    5,    6,    2,    4,    8,    9,    1,    7,   12,   13,   11,
           17,   16,   15,   21,   22,   20,   23,   26,   25,   19,   24,   30,
           31,   29,   34,   33,   35,   28,   32,   39,   40,   38,   41,   37,
           45,   44,   43,   49,   50,   48,   51,   47,   56,   57,   54,   55,
           59,   53,   58,   63,   64,   66,   67,   62,   65,   70,   71,   69,
           61,   68,   75,   77,   74,   76,   73,   81,   83,   80,   82,   86,
           85,   87,   79,   84,   91,   93,   90,   92,   89,   96,   95,   99,
          100,  103,  104,  106,  107,  102,  105,   98,  101,  111,  113,  114,
          110,  112,  109,  118,  119,  121,  117,  120,  124,  125,  127,  128,
          123,  126,  116,  122,  133,  131,  132,  136,  135,  130,  134,  140,
          141,  139,  142,  144,  138,  143,  148,  147,  151,  150,  146,  149,
          155,  157,  158,  154,  156,  160,  153,  159,  163,  165,  162,  164,
          168,  167,  172,  173,  171,  176,  177,  175,  178,  170,  174,  181,
          182,  180,  187,  185,  186,  189,  190,  184,  188,  193,  194,  198,
          196,  197,  192,  195,  202,  204,  205,  201,  203,  207,  200,  206,
          211,  210,  212,  216,  214,  215,  209,  213,  220,  222,  219,  221,
          225,  226,  228,  224,  227,  218,  223,  233,  234,  231,  232,  230,
          238,  239,  237,  240,  236,  244,  243,  246,  242,  245,  250,  251,
          249,  252,  256,  257,  254,  255,  248,  253,  261,  263,  260,  262,
          266,  268,  269,  265,  267,  259,  264,  273,  274,  272,  275,  271,
          279,  278,  282,  284,  285,  281,  283,  277,  280,  289,  290,  292,
          288,  291,  294,  287,  293,  299,  300,  297,  298,  304,  302,  303,
          296,  301,  307,  308,  310,  311,  306,  309,  315,  316,  314,  317,
          313,  320,  322,  319,  321,  326,  327,  325,  324,  331,  332,  330,
          334,  329,  333,  339,  340,  337,  338,  342,  336,  341,  346,  345,
          349,  350,  352,  353,  348,  351,  344,  347,  357,  358,  356,  359,
          363,  364,  361,  362,  355,  360,  368,  370,  371,  367,  369,  373,
          366,  372,  376,  377,  375,  381,  383,  384,  380,  382,  379,  388,
          389,  387,  386,  394,  392,  393,  397,  399,  400,  396,  398,  391,
          395,  404,  403,  402,  408,  409,  411,  412,  407,  410,  406,  416,
          417,  415,  414,  422,  423,  420,  421,  426,  427,  425,  428,  419,
          424,  433,  434,  431,  432,  436,  430,  435,  440,  442,  443,  439,
          441,  438,  448,  449,  446,  447,  452,  454,  455,  451,  453,  445,
          450,  460,  458,  459,  463,  462,  457,  461,  467,  468,  470,  471,
          466,  469,  475,  476,  473,  474,  465,  472,  480,  482,  483,  479,
          481,  486,  485,  478,  484,  489,  488,  492,  495,  494,  496,  491,
          493,  500,  501,  503,  504,  499,  502,  498,  508,  507,  506,  512,
          513,  515,  511,  514,  519,  520,  517,  518,  510,  516,  524,  525,
          523,  528,  527,  522,  526,  533,  531,  532,  530,  537,  536,  538,
          535,  542,  544,  545,  541,  543,  540,  549,  548,  550,  547,  554,
          555,  553,  558,  560,  561,  557,  559,  552,  556,  565,  566,  568,
          564,  567,  571,  570,  563,  569,  575,  577,  578,  574,  576,  581,
          580,  573,  579,  585,  586,  584,  583,  589,  590,  588,  593,  592,
          596,  597,  601,  602,  599,  600,  595,  598,  606,  607,  605,  604,
          612,  610,  611,  609,  616,  615,  617,  614,  621,  622,  624,  625,
          620,  623,  628,  629,  627,  619,  626,  634,  635,  632,  633,  638,
          640,  637,  639,  631,  636,  644,  643,  647,  648,  646,  642,  645,
          652,  653,  651,  650,  657,  659,  656,  658,  655,  662,  663,  666,
          667,  665,  661,  664,  671,  673,  674,  670,  672,  677,  678,  676,
          669,  675,  683,  681,  682,  680,  688,  689,  686,  687,  685,  693,
          692,  696,  698,  695,  697,  691,  694,  702,  703,  701,  707,  708,
          705,  706,  700,  704,  712,  711,  715,  714,  716,  710,  713,  720,
          719,  718,  723,  724,  727,  729,  730,  726,  728,  722,  725,  734,
          736,  733,  735,  739,  740,  742,  743,  738,  741,  732,  737,  747,
          746,  748,  752,  750,  751,  745,  749,  755,  756,  758,  754,  757,
          762,  763,  761,  764,  760,  768,  767,  769,  766,  773,  772,  774,
          771,  777,  780,  782,  779,  781,  776,  778,  786,  785,  787,  784,
          791,  792,  794,  790,  793,  797,  798,  800,  801,  796,  799,  789,
          795,  806,  804,  805,  803,  810,  811,  809,  808,  815,  816,  814,
          813,  820,  822,  823,  819,  821,  825,  818,  824,  829,  830,  828,
          831,  835,  833,  834,  827,  832,  839,  841,  842,  838,  840,  845,
          847,  844,  846,  837,  843,  851,  850,  854,  856,  857,  853,  855,
          849,  852,  861,  862,  860,  866,  867,  864,  865,  859,  863,  872,
          870,  871,  869,  876,  877,  875,  874,  881,  880,  885,  883,  884,
          879,  882,  889,  890,  892,  893,  888,  891,  897,  898,  895,  896,
          887,  894,  902,  901,  900,  907,  905,  906,  904,  911,  913,  914,
          910,  912,  917,  918,  920,  921,  916,  919,  909,  915,  924,  925,
          928,  929,  931,  932,  927,  930,  923,  926,  936,  937,  935,  940,
          942,  943,  939,  941,  934,  938,  947,  948,  950,  946,  949,  945,
          954,  956,  953,  955,  958,  952,  957,  961,  962,  964,  965,  960,
          963,  969,  968,  972,  971,  973,  967,  970,  978,  979,  976,  977,
          982,  983,  981,  975,  980,  988,  986,  987,  985,  991,  994,  995,
          993,  990,  992,  999, 1000, 1002, 1003,  998, 1001,  997, 1008, 1009,
         1006, 1007, 1012, 1011, 1005, 1010, 1016, 1015, 1014, 1020, 1021, 1019,
         1018, 1024, 1023, 1027, 1026, 1031, 1032, 1034, 1035, 1030, 1033, 1029,
         1039, 1040, 1038, 1041, 1037, 1045, 1046, 1048, 1049, 1044, 1047, 1052,
         1053, 1051, 1043, 1050, 1056, 1058, 1059, 1055, 1057, 1062, 1061, 1066,
         1065, 1070, 1071, 1068, 1069, 1064, 1067, 1075, 1077, 1078, 1074, 1076,
         1073, 1081, 1085, 1086, 1083, 1084, 1080, 1082, 1090, 1091, 1089, 1094,
         1096, 1097, 1093, 1095, 1088, 1092, 1101, 1102, 1104, 1105, 1100, 1103,
         1099, 1109, 1108, 1107, 1112, 1113, 1111, 1117, 1119, 1116, 1118, 1115,
         1123, 1124, 1126, 1127, 1122, 1125, 1130, 1131, 1133, 1134, 1129, 1132,
         1121, 1128, 1138, 1139, 1137, 1141, 1142, 1136, 1140, 1145, 1148, 1150,
         1151, 1147, 1149, 1144, 1146, 1156, 1157, 1154, 1155, 1153, 1161, 1162,
         1160, 1165, 1164, 1166, 1159, 1163, 1170, 1171, 1169, 1172, 1175, 1176,
         1174, 1177, 1168, 1173, 1181, 1180, 1182, 1186, 1187, 1184, 1185, 1179,
         1183, 1191, 1192, 1190, 1193, 1195, 1189, 1194, 1198, 1201, 1202, 1204,
         1200, 1203, 1197, 1199, 1208, 1207, 1209, 1212, 1214, 1215, 1211, 1213,
         1206, 1210, 1219, 1220, 1218, 1221, 1225, 1223, 1224, 1217, 1222, 1229,
         1230, 1228, 1231, 1234, 1235, 1233, 1227, 1232, 1239, 1238, 1240, 1243,
         1242, 1244, 1237, 1241, 1248, 1247, 1251, 1252, 1250, 1246, 1249, 1255,
         1256, 1259, 1258, 1254, 1257, 1263, 1264, 1266, 1262, 1265, 1269, 1268,
         1261, 1267, 1273, 1274, 1276, 1277, 1272, 1275, 1271, 1281, 1282, 1280,
         1285, 1286, 1288, 1289, 1284, 1287, 1279, 1283, 1293, 1292, 1294, 1297,
         1298, 1296, 1291, 1295, 1301, 1305, 1303, 1304, 1300, 1302, 1308, 1309,
         1312, 1311, 1313, 1307, 1310, 1317, 1318, 1320, 1316, 1319, 1323, 1324,
         1326, 1322, 1325, 1315, 1321, 1330, 1331, 1329, 1334, 1333, 1335, 1328,
         1332, 1338, 1339, 1342, 1343, 1341, 1337, 1340, 1347, 1348, 1346, 1349,
         1352, 1351, 1353, 1345, 1350, 1357, 1358, 1360, 1356, 1359, 1363, 1364,
         1362, 1355, 1361, 1368, 1370, 1367, 1369, 1373, 1372, 1366, 1371, 1377,
         1378, 1376, 1380, 1375, 1379, 1385, 1383, 1384, 1388, 1389, 1391, 1387,
         1390, 1382, 1386, 1395, 1394, 1396, 1393, 1399, 1402, 1401, 1403, 1398,
         1400, 1407, 1408, 1406, 1409, 1405, 1412, 1416, 1414, 1415, 1411, 1413,
         1420, 1422, 1423, 1419, 1421, 1426, 1425, 1418, 1424, 1429, 1430, 1432,
         1433, 1428, 1431, 1437, 1439, 1440, 1436, 1438, 1443, 1444, 1442, 1445,
         1435, 1441, 1448, 1451, 1450, 1447, 1449, 1455, 1456, 1454, 1459, 1461,
         1458, 1460, 1453, 1457, 1465, 1464, 1466, 1468, 1463, 1467, 1472, 1473,
         1475, 1476, 1471, 1474, 1470, 1481, 1482, 1479, 1480, 1485, 1486, 1484,
         1478, 1483, 1489, 1490, 1488, 1494, 1495, 1497, 1493, 1496, 1500, 1501,
         1499, 1492, 1498, 1504, 1503, 1508, 1509, 1507, 1512, 1513, 1515, 1511,
         1514, 1506, 1510, 1518, 1521, 1522, 1520, 1517, 1519, 1526, 1528, 1525,
         1527, 1524, 1533, 1534, 1531, 1532, 1537, 1538, 1540, 1541, 1536, 1539,
         1530, 1535, 1545, 1547, 1548, 1544, 1546, 1543, 1552, 1553, 1551, 1550,
         1558, 1559, 1556, 1557, 1555, 1562, 1565, 1566, 1568, 1569, 1564, 1567,
         1561, 1563]])


In [28]:
edge_attr = torch.tensor([[1.]]*1370)

In [29]:
import torch
from torch_scatter import scatter

# Example inputs
edge_index = edge_index
edge_attr = edge_attr.squeeze()  # optional, can be None
batch = None  # No batch information, single graph
batch_size = None  # Not specified
max_num_nodes = None  # Not specified

# The script
if batch is None:
    num_nodes = int(edge_index.max()) + 1 if edge_index.numel() > 0 else 0
    batch = edge_index.new_zeros(num_nodes)

if batch_size is None:
    batch_size = int(batch.max()) + 1 if batch.numel() > 0 else 1

one = batch.new_ones(batch.size(0))
num_nodes = scatter(one, batch, dim=0, dim_size=batch_size, reduce='sum')
cum_nodes = torch.cat([batch.new_zeros(1), num_nodes.cumsum(dim=0)])

idx0 = batch[edge_index[0]]
idx1 = edge_index[0] - cum_nodes[batch][edge_index[0]]
idx2 = edge_index[1] - cum_nodes[batch][edge_index[1]]

if max_num_nodes is None:
    max_num_nodes = int(num_nodes.max())

elif ((idx1.numel() > 0 and idx1.max() >= max_num_nodes)
      or (idx2.numel() > 0 and idx2.max() >= max_num_nodes)):
    mask = (idx1 < max_num_nodes) & (idx2 < max_num_nodes)
    idx0 = idx0[mask]
    idx1 = idx1[mask]
    idx2 = idx2[mask]
    edge_attr = None if edge_attr is None else edge_attr[mask]

if edge_attr is None:
    edge_attr = torch.ones(idx0.numel(), device=edge_index.device)

size = [batch_size, max_num_nodes, max_num_nodes]
size += list(edge_attr.size())[1:]
flattened_size = batch_size * max_num_nodes * max_num_nodes

idx = idx0 * max_num_nodes * max_num_nodes + idx1 * max_num_nodes + idx2
adj = scatter(edge_attr, idx, dim=0, dim_size=flattened_size, reduce='sum')
adj = adj.view(size)

print(adj)


tensor([[[0., 1., 0.,  ..., 0., 0., 0.],
         [0., 0., 1.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 1., 1.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])


In [36]:
import torch.nn.functional as F

In [37]:
preds = torch.tensor([[1.1938],
        [1.2945],
        [1.2502],
        [1.2253],
        [1.2125],
        [1.2182]])

In [38]:
target = preds = torch.tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [40]:
F.cross_entropy(preds.squeeze(), target.squeeze(), reduction='sum')

tensor(10.7506)

In [ ]:
"data/qm9/qm9_pyg/processed/proc_val_no_h.pt"

In [4]:
# Import necessary libraries
import torch
from torch_geometric.data import Data
import matplotlib.pyplot as plt
import pandas as pd
from collections import defaultdict

# Load the dataset
dataset_path = "data/qm9/qm9_pyg/processed/proc_val_no_h.pt"
dataset_path2 = "data/symbolic/processed/val.pt"
dataset = torch.load(dataset_path2)

for data in dataset:
    print(data.x.shape)

torch.Size([15653, 15])


AttributeError: 'dict' object has no attribute 'x'

In [42]:
y=torch.tensor([], dtype=float)

In [52]:
s_array =  8 * torch.zeros((200, 1)).type_as(y) + 3
s_array

tensor([[3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
        [3.],
      

In [4]:
import numpy as np
import sympy as sp
import matplotlib.pyplot as plt
import random
import pandas as pd

import torch
import networkx as nx
from torch_geometric.data import Data
from torch_geometric.utils import to_networkx
from src.datasets.abstract_dataset import AbstractDataModule, AbstractDatasetInfos
from torch_geometric.data import Data, InMemoryDataset
from src.utils import count_node_connections

from IPython.display import display, Image
from graphviz import Digraph

import pathlib
import os

from src.constants import UNARY, BINARY, MAX_DEPTH, N_FEATURES, NODE_TYPES, N_SAMPLES, MAX_LOG10_VAL, MIN_LOG10_VAL


print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA device count: {torch.cuda.device_count()}")
if torch.cuda.is_available():
    print(f"Device Name: {torch.cuda.get_device_name(0)}")
    print(f"Current Device: {torch.cuda.current_device()}")
else:
    print("CUDA is not available. Using CPU instead.")


def generate_random_constant():
    """
    Generates a random constant.

    Returns:
        float: A random constant generated by raising 10 to a random power between -10 and 10.
    """
    pow = random.uniform(-10, 10)
    return 10**pow

def generate_expression_tree(max_depth=MAX_DEPTH, node_types=NODE_TYPES, current_depth=0):
    """
    Generates a random expression tree.

    Parameters:
        max_depth (int): The maximum depth of the tree.
        node_types (dict): Dictionary containing the types of nodes (operands, operators, unary_operators).

    Returns:
        tuple/str/float: A randomly generated expression tree.
    """
    
    if current_depth >= 2 and (max_depth == 0 or random.random() < 0.3):
        if random.random() < 2:#0.5:
            return random.choice(node_types['operands'])
        else:
            return generate_random_constant()

    operator = random.choice(node_types['operators'])
    if operator in node_types['unary_operators']:
        operand = generate_expression_tree(max_depth - 1, node_types, current_depth + 1)
        if operator == 'log':
            while isinstance(operand, (int, float)) and operand <= 0:
                operand = generate_random_constant()
        return (operator, operand)
    else:
        left = generate_expression_tree(max_depth - 1, node_types, current_depth + 1)
        right = generate_expression_tree(max_depth - 1, node_types, current_depth + 1)
        return (operator, left, right)

def tree_to_graph(tree, node_types=NODE_TYPES):
    """
    Converts an expression tree to a graph.

    Parameters:
        tree (tuple/str/float): The expression tree.

    Returns:
        Data: A PyTorch Geometric Data object representing the graph.
    """
    nodes = []
    edges = []
    node_features = []

    def add_node(node):
        if isinstance(node, tuple):
            operator = node[0]
            node_id = len(nodes)
            nodes.append(operator)
            node_features.append(
                [int(operator == op) for op in node_types['operators']] + 
                [0] * len(node_types['operands']) + 
                [0, 0.0]  # Placeholder for constant flag and value
            )
            
            if operator in node_types['unary_operators']:  # Unary operators
                child_id = add_node(node[1])
                edges.append([node_id, child_id])
            else:  # Binary operators
                left_id = add_node(node[1])
                right_id = add_node(node[2])
                edges.append([node_id, left_id])
                edges.append([node_id, right_id])
            
            return node_id
        else:
            node_id = len(nodes)
            nodes.append(node)
            if isinstance(node, (int, float)):  # Handle constants
                node_features.append(
                    [0] * (len(node_types['operators'])) + 
                    [0] * len(node_types['operands']) + 
                    [1, node]  # Flag indicating this is a constant and the constant value
                )
            else:  # Handle operands
                node_features.append(
                    [0] * (len(node_types['operators'])) + 
                    [int(node == op) for op in node_types['operands']] + 
                    [0, 0.0]  # Placeholder for constant flag and value
                )
            return node_id
    
    root_id = add_node(tree)

    if len(edges) == 0:
        edge_index = torch.empty((2, 0), dtype=torch.long)  # Handle the case where no edges are generated
    else:
        edge_index = torch.tensor(edges, dtype=torch.long).t().contiguous()
 
    x = torch.tensor(node_features, dtype=torch.float)

    if edge_index.numel() == 0:
        edge_attr = torch.empty((0, 2), dtype=torch.float)  # Handle the case where no edges are generated
    else:
        edge_attr = torch.ones((edge_index.size(1), 2), dtype=torch.float)  # Set edge attributes to [0, 1]
    # Manually set the first column to 0
    edge_attr[:, 1] = 0

    edge_counts = count_node_connections(edge_index)
    # x = torch.cat([x, torch.tensor(edge_counts, dtype=torch.float).view(-1, 1)], dim=1)

    y = torch.zeros((1, 0), dtype=torch.float)

    return Data(x=x, edge_index=edge_index, edge_attr=edge_attr, y=y)

def get_label(node_feature, node_types=NODE_TYPES):
    """
    Gets the label for a node based on its features.

    Parameters:
        node_feature (list): The feature vector of the node.

    Returns:
        str/float: The label of the node.
    """
    node_feature = torch.tensor(node_feature)  # Ensure node_feature is a tensor
    if node_feature[0:len(node_types['operators']), 0].sum()==1:  # Operator
        index = int(torch.argmax(node_feature[1:len(node_types['operators']) + 1]))
        return node_types['operators'][index]
    elif node_feature[-2, 0] == 1:  # Constant
        return float(node_feature[-1, 0].item())  # Decode the constant value
    else:  # Operand
        index = int(torch.argmax(node_feature[len(node_types['operators']) + 1:-2, 0]))
        return node_types['operands'][index]

def graph_to_tree(data):
    """
    Converts a graph back to an expression tree.

    Parameters:
        data (Data): A PyTorch Geometric Data object representing the graph.

    Returns:
        tuple/str/float: The reconstructed expression tree.
    """
    G = to_networkx(data, node_attrs=['x'])
    labels = {i: get_label(node['x']) for i, node in G.nodes(data=True)}
    
    def build_tree(node):
        neighbors = list(G.neighbors(node))
        if len(neighbors) == 0:
            return labels[node]
        elif len(neighbors) == 1:
            return (labels[node], build_tree(neighbors[0]))
        else:
            left_subtree = build_tree(neighbors[0])
            right_subtree = build_tree(neighbors[1])
            return (labels[node], left_subtree, right_subtree)
    
    root = 0  # Assuming the root node is always node 0
    return build_tree(root)

def tree_to_sympy(tree):
    """
    Converts an expression tree to a SymPy expression.

    Parameters:
        tree (tuple/str/float): The expression tree.

    Returns:
        Basic: The SymPy expression.
    """
    if isinstance(tree, str):  # Operand
        return sp.symbols(tree)
    elif isinstance(tree, (int, float)):  # Constant
        return tree
    operator, *operands = tree
    sympy_operands = [tree_to_sympy(op) for op in operands]
    if operator == 'exp':
        return sp.exp(sympy_operands[0])
    elif operator == 'log':
        return sp.log(sympy_operands[0])
    elif operator == 'inv':
        return 1 / sympy_operands[0]
    elif operator == '+':
        return sympy_operands[0] + sympy_operands[1]
    elif operator == '-':
        return sympy_operands[0] - sympy_operands[1]
    elif operator == '*':
        return sympy_operands[0] * sympy_operands[1]
    elif operator == '/':
        return sympy_operands[0] / sympy_operands[1]

def visualize_tree(tree, node_id=0, graph=None, parent_id=None):
    """
    Visualizes an expression tree using Graphviz.

    Parameters:
        tree (tuple/str/float): The expression tree.
        node_id (int): The current node ID (default is 0).
        graph (Digraph): The current Graphviz Digraph object (default is None).
        parent_id (int): The parent node ID (default is None).

    Returns:
        Digraph: The Graphviz Digraph object representing the tree.
    """
    if graph is None:
        graph = Digraph()
    
    if isinstance(tree, tuple):
        operator = tree[0]
        graph.node(str(node_id), operator)
        if parent_id is not None:
            graph.edge(str(parent_id), str(node_id))
        
        child_id = node_id + 1
        graph = visualize_tree(tree[1], child_id, graph, node_id)
        if len(tree) > 2:
            sibling_id = child_id + count_nodes(tree[1])
            graph = visualize_tree(tree[2], sibling_id, graph, node_id)
    else:
        graph.node(str(node_id), str(tree))
        if parent_id is not None:
            graph.edge(str(parent_id), str(node_id))
    
    return graph

def count_nodes(tree):
    """
    Counts the number of nodes in an expression tree.

    Parameters:
        tree (tuple/str/float): The expression tree.

    Returns:
        int: The number of nodes in the tree.
    """
    if isinstance(tree, tuple):
        operator = tree[0]
        if len(tree) == 2:  # Unary operator
            return 1 + count_nodes(tree[1])
        else:  # Binary operator
            return 1 + count_nodes(tree[1]) + count_nodes(tree[2])
    else:
        return 1

def display_tree(tree):
    """
    Displays an expression tree using Graphviz and IPython.

    Parameters:
        tree (tuple/str/float): The expression tree.
    """
    graph = visualize_tree(tree)
    graph.format = 'png'
    graph.render(filename='expression_tree', view=False)
    display(Image(filename='expression_tree.png'))

def generate_random_table(n_features=N_FEATURES, 
                          n_samples=N_SAMPLES, 
                          min_log10=MIN_LOG10_VAL, 
                          max_log10=MAX_LOG10_VAL):
    """
    Generates a table of random values for n features between min_value and max_value.

    Parameters:
        n_features (int): Number of features (columns).
        n_samples (int): Number of samples (rows).
        min_log10 (int): Minimum log10 value for random data generation.
        max_log10 (int): Maximum log10 value for random data generation.

    Returns:
        DataFrame: A Pandas DataFrame containing the random values.
    """
    random_data = 10 ** np.random.uniform(low=min_log10, high=max_log10, size=(n_samples, n_features))
    feature_names = [f'x{i}' for i in range(n_features)]
    
    df = pd.DataFrame(random_data, columns=feature_names)
    
    return df

def generate_graph_and_data(max_depth=MAX_DEPTH,
                            node_types=NODE_TYPES,
                            n_features=N_FEATURES, 
                            n_samples=N_SAMPLES, 
                            min_log10=MIN_LOG10_VAL, 
                            max_log10=MAX_LOG10_VAL):
    """
    Generates a random expression tree, converts it to a graph, and generates corresponding data.

    Parameters:
        max_depth (int): The maximum depth of the tree.
        n_features (int): The number of features.
        n_samples (int): The number of samples.
        min_log10 (int): Minimum log10 value for random data generation.
        max_log10 (int): Maximum log10 value for random data generation.

    Returns:
        tuple: A tuple containing the graph (Data) and the dataset (DataFrame).
    """
    tree = generate_expression_tree(max_depth, node_types)
    graph = tree_to_graph(tree, node_types)

    sympy_expr = tree_to_sympy(tree)
    features_tuple = tuple(['x' + str(i) for i in range(n_features)])
    sympy_lambda = sp.lambdify(features_tuple, sympy_expr, 'numpy')

    dataset = generate_random_table(n_features, n_samples, min_log10, max_log10)
    dataset['y'] = dataset.apply(lambda row: sympy_lambda(*tuple(row)), axis=1)

    return graph, dataset


class GeneratedGraphDataset(InMemoryDataset):
    def __init__(self, split, root, transform=None, pre_transform=None, pre_filter=None):
        self.split = split
        self.num_graphs = 2000
        super().__init__(root, transform, pre_transform, pre_filter)
        self.data, self.slices = torch.load(self.processed_paths[0])

    @property
    def raw_file_names(self):
        return ['train.pt', 'val.pt', 'test.pt']

    @property
    def processed_file_names(self):
        return [self.split + '.pt']

    def download(self):
        pass

    def process(self):
        data_list = []
        for _ in range(self.num_graphs):
            graph = tree_to_graph(generate_expression_tree())
            data_list.append(graph)
        print('Dataset generation done')

        torch.save(self.collate(data_list), self.processed_paths[0])


class GeneratedGraphDataModule(AbstractDataModule):
    def __init__(self, cfg, n_graphs=2000):
        self.cfg = cfg
        self.datadir = cfg.dataset.datadir
        base_path = pathlib.Path(os.path.realpath(__file__)).parents[2]
        root_path = os.path.join(base_path, self.datadir)
        datasets = {
            'train': GeneratedGraphDataset(split='train', root=root_path),
            'val': GeneratedGraphDataset(split='val', root=root_path),
            'test': GeneratedGraphDataset(split='test', root=root_path)
        }

        super().__init__(cfg, datasets)
        self.inner = self.train_dataset

    def __getitem__(self, item):
        return self.inner[item]


class GeneratedDatasetInfos(AbstractDatasetInfos):
    def __init__(self, datamodule, dataset_config):
        self.datamodule = datamodule
        self.name = 'generated_graphs'
        self.n_nodes = self.datamodule.node_counts()
        self.node_types = self.datamodule.node_types()
        self.edge_types = self.datamodule.edge_counts()
        super().complete_infos(self.n_nodes, self.node_types)

PyTorch version: 2.4.0
CUDA available: False
CUDA device count: 0
CUDA is not available. Using CPU instead.


In [5]:
GeneratedGraphDataset(split='train', root='data')

Processing...


Dataset generation done


Done!
/var/folders/pn/khhmnw650hb1xn7840m6mw8m0000gp/T/ipykernel_51138/3805669859.py:352: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.data, self.slices = torch.load(s

GeneratedGraphDataset(2000)

In [6]:
import torch

# Load the .pt file
file_path = "data/processed/train.pt"  # replace with your .pt file path
data_list, slices = torch.load(file_path)
print(slices)
# Print details for each graph
for i, graph in enumerate(data_list):
    print(graph)

{'x': tensor([    0,     6,    15,  ..., 15710, 15713, 15719]), 'edge_index': tensor([    0,     5,    13,  ..., 13712, 13714, 13719]), 'edge_attr': tensor([    0,     5,    13,  ..., 13712, 13714, 13719]), 'y': tensor([   0,    1,    2,  ..., 1998, 1999, 2000])}
('x', tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]]))
('edge_index', tensor([[2, 2, 1,  ..., 1, 1, 0],
        [3, 4, 2,  ..., 2, 3, 1]]))
('edge_attr', tensor([[1., 0.],
        [1., 0.],
        [1., 0.],
        ...,
        [1., 0.],
        [1., 0.],
        [1., 0.]]))
('y', tensor([], size=(2000, 0)))


/var/folders/pn/khhmnw650hb1xn7840m6mw8m0000gp/T/ipykernel_51138/4007804667.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data_list, slices = torch.load(file_path)


In [8]:
# Load the dataset
dataset = GeneratedGraphDataset(split='train', root='data/')

# Access each graph automatically
print(f"Total graphs in dataset: {len(dataset)}")
for i in range(len(dataset)):
    graph = dataset[i]  # Automatically reconstructs the i-th graph
    print(f"Graph {i}:")
    print(graph.edge_index)

Total graphs in dataset: 2000
Graph 0:
tensor([[2, 2, 1, 1, 0],
        [3, 4, 2, 5, 1]])
Graph 1:
tensor([[2, 1, 1, 6, 5, 5, 0, 0],
        [3, 2, 4, 7, 6, 8, 1, 5]])
Graph 2:
tensor([[2, 2, 5, 5, 1, 1, 0],
        [3, 4, 6, 7, 2, 5, 1]])
Graph 3:
tensor([[3, 1, 1, 5, 0, 0],
        [4, 2, 3, 6, 1, 5]])
Graph 4:
tensor([[2, 2, 1, 6, 8, 5, 5, 0, 0],
        [3, 4, 2, 7, 9, 6, 8, 1, 5]])
Graph 5:
tensor([[2, 4, 4, 1, 1, 7, 0, 0],
        [3, 5, 6, 2, 4, 8, 1, 7]])
Graph 6:
tensor([[2, 1, 0],
        [3, 2, 1]])
Graph 7:
tensor([[ 3,  3,  1,  1,  7,  7, 10, 10,  6,  6,  0,  0],
        [ 4,  5,  2,  3,  8,  9, 11, 12,  7, 10,  1,  6]])
Graph 8:
tensor([[ 2,  4,  4,  1,  1,  8,  8, 11, 11,  7,  7,  0,  0],
        [ 3,  5,  6,  2,  4,  9, 10, 12, 13,  8, 11,  1,  7]])
Graph 9:
tensor([[2, 2, 1, 0],
        [3, 4, 2, 1]])
Graph 10:
tensor([[2, 2, 1, 6, 8, 5, 5, 0, 0],
        [3, 4, 2, 7, 9, 6, 8, 1, 5]])
Graph 11:
tensor([[2, 2, 1, 0],
        [3, 4, 2, 1]])
Graph 12:
tensor([[ 2,  2,  5,

/var/folders/pn/khhmnw650hb1xn7840m6mw8m0000gp/T/ipykernel_51138/3805669859.py:352: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.data, self.slices = torch.load(self.pr

In [93]:
import torch

# Load the .pt file
file_path = "data/symbolic/processed/train.pt"  # replace with your .pt file path
data, slices = torch.load(file_path)


# Function to extract a single graph by index
def extract_graph(data, slices, idx):
    graph = Data()
    for key in data._store:  # Iterate over data attributes directly
        item = data[key]
        if torch.is_tensor(item):
            # Use slices to extract the individual graph's data
            start, end = slices[key][idx], slices[key][idx + 1]
            graph[key] = item[start:end]
        else:
            graph[key] = item
    return graph

# Retrieve the first graph
graph_0 = extract_graph(data, slices, 4)
print(graph_0)  # This should now be the first individual graph as a Data object

Data(x=[12, 14], edge_index=[0, 13774], edge_attr=[11, 2], y=[1, 0])


/var/folders/pn/khhmnw650hb1xn7840m6mw8m0000gp/T/ipykernel_69578/3547128989.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data, slices = torch.load(file_path)
